# Generated by Django 4.2.5 on 2023-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("date", models.CharField(max_length=200)),
                ("img", models.TextField()),
                (
                    "booking",
                    models.CharField(
                        choices=[("yes", "館藏中"), ("no", "外借中")],
                        default="yes",
                        max_length=3,
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("pub_date",),},
        ),
    ]
