# Generated by Django 4.2.6 on 2024-01-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_post_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('img', models.TextField()),
                ('booking', models.CharField(choices=[('In Library', '館藏中'), ('Reserverd', '預約中'), ('On load', '外借中')], default='In Library', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
