# Generated by Django 4.2.5 on 2024-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytest", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyFormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mood", models.CharField(max_length=255)),
                ("user_post", models.TextField()),
                ("user_id", models.CharField(max_length=255)),
                ("user_pass", models.CharField(max_length=255)),
                ("pub_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
